import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      marginTop:35,
      backgroundColor: '#f5f5f5',
      alignItems: 'center',
      alignContent:'center'
    },
    header:{
      flex:0.1,
      flexDirection:'row',
      justifyContent:'space-between',
      width:350,
     
    },
    body:{
      flex:1,
      alignItems:'center',
      justifyContent:'center',
    },
    addfield:{
      flex:0.2,
      width:400,
      alignItems:'flex-end',
    },
    touchablefield:{
      width:100,
      height:100,
      alignItems:'center',
      justifyContent:'center',
    },
    clickable:{
      width:70,
      height:70,
      fontSize:45,
      color:'white',
      backgroundColor:'black',
      textAlign:'center',
      borderRadius:40,
    },
    searchcontainer:{
      borderColor:'transparent',
      borderWidth:2,
      width:350,
      borderRadius:15,
      backgroundColor:'#f0ebeb',
      flexDirection:'row',
      alignItems:'center',
      padding:5,
      paddingLeft:13
    },
    searchbar:{
     paddingLeft:10,
    },
    noteside: {
      width:27,
      height:27,
    },
    todoside:{
      height:27,
      width:27,
    },
    AddingThings:{
      borderColor:'transparent',
      borderWidth:2,
      width:400,
      height:80,
      borderRadius:20,
      backgroundColor:'#f0ebeb',
      flexDirection:'row',
      justifyContent:'space-between',
      alignItems:'center',
      padding:5,
      paddingLeft:13
    },
    TasksInTheArray:{
      borderColor:'transparent',
      borderWidth:2,
      width:370,
      height:60,
      borderRadius:20,
      backgroundColor:'#fff',
      flexDirection:'row',
      justifyContent:'space-evenly',
      alignItems:'center',
      padding:5,
      marginTop:10,
      
    },
    TasksBox:{
      backgroundColor:'#fafafa',
      width:20,
      height:20,
      borderRadius:5,
      borderWidth:1,
      borderColor:'gray',
      alignItems:'center',
    },
    DeleteField:{
      width:400,
      height:150,
      alignItems:'center',
      justifyContent:'center',
    },
    showthings:{

    },
    TaskAddBar:{
      backgroundColor:'white',
      width:300,
      height:20,
    },
    TasksProperties:{
      width:300,
      height:20,
      textDecorationLine:'line-through',
    },
    box:{
      backgroundColor:'white',
      width:20,
      height:20,
      borderRadius:5,
      borderColor:'black',
      borderWidth:1,
    },
    circle:{
      backgroundColor:'white',
      width:20,
      height:20,
      borderRadius:15,
      borderColor:'black',
      borderWidth:1,
    },
  });